config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :hello, only: [:show], controller: :static_pages, action: :hello

  root controller: :static_pages, action: :home
  resource :home, only: [:show], controller: :static_pages, action: :home
  resource :about, only: [:show], controller: :static_pages, action: :about

  get '/signup', controller: :accounts, action: :new
  post '/signup', controller: :accounts, action: :create

  get '/login', controller: :sessions, action: :new
  post '/login', controller: :sessions, action: :create
  delete '/logout', controller: :sessions, action: :destroy

  resources :account_activations, param: :activation_token, only: [:edit]
  resources :password_resets, param: :reset_token, only: [:new, :create, :edit, :update]

  resources :lunches, only: [:create, :destroy], param: :lunch_id

  get '/users', controller: :accounts, action: :index
  resources :accounts, only: [:update], param: :account_id
  resources :accounts, only: [:edit], param: :account_name do
    member do
      get :following, :followers
    end
  end
  resources :account_relationships, only: [:create, :destroy],
                                    param: :account_relationship_id
  get '/accounts/:account_name', controller: :accounts, action: :show,
                                 to: redirect('/%<account_name>s')
  get '/:account_name', controller: :accounts, action: :show, as: :short_account
end

app/views/shared/_account_info.html.erb
<%= link_to gravatar_for(current_account, size: 50), current_account.account_name %>
<h1><%= current_account.account_name %></h1>
<span><%= pluralize(current_account.lunches.count, "lunch") %></span>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="lunches">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_lunch_form.html.erb
<%= form_for(@lunch) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <div class="controls">
      <%= f.label :date %>
      <%= f.text_field :lunch_date,
                       data: { date_format: "YYYY-MM-DD" },
                       class: "form-control datetimepicker",
                       value: Time.zone.now.in_time_zone('Asia/Tokyo').strftime('%Y-%m-%d') %>
    </div>
    <%= f.label :comment %>
    <%= f.text_area :comment, placeholder: "Compose lunch comment..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @account ||= current_account %>
<div class="stats">
  <a href="<%= following_account_path(@account.account_name) %>">
    <strong id="following" class="stat">
      <%= @account.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_account_path(@account.account_name) %>">
    <strong id="followers" class="stat">
      <%= @account.followers.count %>
    </strong>
    followers
  </a>
</div>