config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :hello, only: [:show], controller: :static_pages, action: :hello

  root controller: :static_pages, action: :home
  resource :home, only: [:show], controller: :static_pages, action: :home
  resource :about, only: [:show], controller: :static_pages, action: :about

  get '/signup', controller: :accounts, action: :new
  post '/signup', controller: :accounts, action: :create

  get '/login', controller: :sessions, action: :new
  post '/login', controller: :sessions, action: :create
  delete '/logout', controller: :sessions, action: :destroy

  resources :account_activations, param: :activation_token, only: [:edit]
  resources :password_resets, param: :reset_token, only: [:new, :create, :edit, :update]

  resources :lunches, only: [:create, :destroy], param: :lunch_id

  get '/users', controller: :accounts, action: :index
  resources :accounts, only: [:update], param: :account_id
  resources :accounts, only: [:edit], param: :account_name do
    member do
      get :following, :followers
    end
  end
  resources :account_relationships, only: [:create, :destroy],
                                    param: :account_relationship_id
  get '/accounts/:account_name', controller: :accounts, action: :show,
                                 to: redirect('/%<account_name>s')
  get '/:account_name', controller: :accounts, action: :show, as: :short_account
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <%= link_to "Serious Lunch", "https://github.com/dyoshimitsu/serious-lunch", target: :_blank, rel: :noopener %>
    by <%= link_to "dyoshimitsu", "https://github.com/dyoshimitsu", target: :_blank, rel: :noopener %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Serious Lunch", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_account.account_name %></li>
              <li><%= link_to "Settings", edit_account_path(current_account.account_name) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= dynamic_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>