config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :hello, only: [:show], controller: :static_pages, action: :hello

  root controller: :static_pages, action: :home
  resource :home, only: [:show], controller: :static_pages, action: :home
  resource :about, only: [:show], controller: :static_pages, action: :about

  get '/signup', controller: :accounts, action: :new
  post '/signup', controller: :accounts, action: :create

  get '/login', controller: :sessions, action: :new
  post '/login', controller: :sessions, action: :create
  delete '/logout', controller: :sessions, action: :destroy

  resources :account_activations, param: :activation_token, only: [:edit]
  resources :password_resets, param: :reset_token, only: [:new, :create, :edit, :update]

  resources :lunches, only: [:create, :destroy], param: :lunch_id

  get '/users', controller: :accounts, action: :index
  resources :accounts, only: [:update], param: :account_id
  resources :accounts, only: [:edit], param: :account_name do
    member do
      get :following, :followers
    end
  end
  resources :account_relationships, only: [:create, :destroy],
                                    param: :account_relationship_id
  get '/accounts/:account_name', controller: :accounts, action: :show,
                                 to: redirect('/%<account_name>s')
  get '/:account_name', controller: :accounts, action: :show, as: :short_account
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  VALID_EMAIL_ADDRESS_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  has_secure_password
  has_many :lunches, dependent: :destroy
  has_many :account_active_relationships,
           class_name: 'AccountRelationship',
           foreign_key: 'follower_account_id',
           dependent: :destroy
  has_many :account_passive_relationships,
           class_name: 'AccountRelationship',
           foreign_key: 'followed_account_id',
           dependent: :destroy
  has_many :following, through: :account_active_relationships, source: :followed_account
  has_many :followers, through: :account_passive_relationships, source: :follower_account
  has_one :account_activation, dependent: :destroy
  has_one :account_cookie, dependent: :destroy
  has_one :account_reset, dependent: :destroy

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save { email_address.downcase! }
  # before_create :create_activation_digest

  validates_with Validators::NonAccountNameValidator
  validates :account_name,
            presence: true,
            length: { maximum: 50 },
            format: { with: /\A[0-9a-zA-Z_]+\z/ },
            uniqueness: { case_sensitive: false }
  validates :password,
            presence: true,
            length: { minimum: 8 },
            allow_nil: true
  validates :email_address,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_ADDRESS_REGEX },
            uniqueness: { case_sensitive: false }

  def feed
    following_ids = "SELECT followed_account_id FROM account_relationships
                     WHERE follower_account_id = :account_id"
    Lunch.where("account_id IN (#{following_ids})
                 OR account_id = :account_id", account_id: account_id)
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  before_action :logged_in_account, only: [:index, :edit, :update, :following, :followers]

  def new
    @account = Account.new
  end

  def index
    @accounts = Account.left_outer_joins(:account_activation)
                       .where(account_activations: { activated: true })
                       .paginate(page: params[:page])
                       .order(:account_name)
  end

  def show
    @account = Account.find_by(account_name: params[:account_name])
    if @account
      @lunches = @account.lunches
                         .order(lunch_date: :desc)
                         .paginate(page: params[:page])
    else
      render file: Rails.root.join('public/404.html'),
             status: 404,
             layout: false,
             content_type: 'text/html'
    end
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      Account::AccountActivator.new(account: @account).account_activation
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def update
    @account = Account.find(params[:account_id])
    if @account != current_account
      redirect_to root_url
    elsif @account.update_attributes(account_params)
      flash[:success] = 'Profile updated'
      redirect_to short_account_url(@account.account_name)
    else
      render 'edit'
    end
  end

  def edit
    @account = Account.find_by(account_name: params[:account_name])
    redirect_to(root_url) unless @account == current_account
  end

  def following
    @title = 'Following'
    @account = Account.find_by(account_name: params[:account_name])
    if @account
      @accounts = @account.following.paginate(page: params[:page]).reload
      render 'show_follow'
    else
      render file: Rails.root.join('public/404.html'),
             status: 404,
             layout: false,
             content_type: 'text/html'
    end
  end

  def followers
    @title = 'Followers'
    @account = Account.find_by(account_name: params[:account_name])
    if @account
      @accounts = @account.followers.paginate(page: params[:page]).reload
      render 'show_follow'
    else
      render file: Rails.root.join('public/404.html'),
             status: 404,
             layout: false,
             content_type: 'text/html'
    end
  end

  private

  def account_params
    params.require(:account).permit(
      :account_name,
      :email_address,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/accounts_helper.rb
# frozen_string_literal: true

module AccountsHelper

  def gravatar_for(account, size: 80)
    gravatar_id = Digest::MD5.hexdigest(account.email_address.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: account.account_name, class: 'gravatar')
  end
end

app/views/accounts/_account.html.erb
<li>
  <%= gravatar_for account, size: 50 %>
  <%= link_to account.account_name, short_account_path(account.account_name) %>
</li>

app/views/accounts/_follow.html.erb
<%= form_for(current_account.account_active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_account_id, @account.account_id %></div>
  <%= f.submit "Follow", class: "btn btn-default" %>
<% end %>

app/views/accounts/_follow_form.html.erb
<% unless current_account?(@account) %>
  <div id="follow_form">
    <% if Account::AccountFollower.new(account: current_account).following?(@account) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/accounts/_unfollow.html.erb
<%= form_for(current_account.account_active_relationships.find_by(followed_account_id: @account.account_id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Following", class: "btn btn-primary" %>
<% end %>

app/views/accounts/edit.html.erb
<% provide(:title, "Profile") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@account) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :account_name, class: 'form-control' %>

      <%= f.label :email_address %>
      <%= f.email_field :email_address, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @account%>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="accounts">
  <%= render @accounts %>
</ul>

<%= will_paginate %>

app/views/accounts/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@account, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :account_name, "Name" %>
      <%= f.text_field :account_name, class: 'form-control' %>

      <%= f.label :email_address %>
      <%= f.email_field :email_address, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<% provide(:title, @account.account_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="account_info">
      <h1>
        <%= gravatar_for @account %>
        <%= @account.account_name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @account.lunches.any? %>
      <h3>Lunch (<%= @account.lunches.count %>)</h3>
      <ol class="lunches">
        <%= render @lunches %>
      </ol>
      <%= will_paginate @lunches %>
    <% end %>
  </div>
</div>

app/views/accounts/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="account_info">
      <%= gravatar_for @account %>
      <h1><%= @account.account_name %></h1>
      <span><%= link_to "view my profile", short_account_path(@account.account_name) %></span>
      <span><b>Lunches:</b> <%= @account.lunches.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @accounts.any? %>
        <div class="account_avatars">
          <% @accounts.each do |account| %>
            <%= link_to gravatar_for(account, size: 30), short_account_path(account.account_name) %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @accounts.any? %>
      <ul class="accounts follow">
        <%= render @accounts %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>